version: 2
multi-ecosystem-groups:
  repo-dependencies:
    schedule:
      interval: "monthly"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "repo-dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "repo-dependencies"
    open-pull-requests-limit: 0
